# Generated by Django 5.1.1 on 2024-11-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(default='admin', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
